### ISSUE TITLE
Scrivomatic fails to process files with spaces in the name

### ISSUE THREAD

**Issue by oWretch** [iandol/scrivomatic#12]
Hi Ian,

I've noticed that Scrivomatic is not happy when passed an input file with a space in the name (e.g., `My File.md`). It doesn't matter if I escape the space with `\`, or enclose the name in double quotes. Either way, Scrivomatic fails with

`!!!---Scrivomatic: could not find My\ File.tex`

Is it possible to add support for file names with spaces?

**Comment by iandol** [comment]
OK, let me have a look at this, it should be able to handle this (I use a ruby shell library to do this but I may be doing something wrong somewhere else)...

**Comment by iandol** [comment]
@oWretch — Hi, I can't actually reproduce this, if I use:

```bash
❯ scrivomatic -v Behaviour\ Platform.txt
```

I get the input properly escaped. I am using the [ShellWords](https://ruby-doc.org/stdlib-2.3.0/libdoc/shellwords/rdoc/Shellwords.html) library on all input and it should properly handle spaces whether they are escaped or not. I also tried:

```bash
❯ scrivomatic -v "Behaviour Platform.txt"
❯ scrivomatic -v -i Behaviour\ Platform.txt
❯ scrivomatic -v -i "Behaviour Platform.txt"
```

They also all worked. Perhaps you are using an older scrivomatic or ruby? Please let me know what version of ruby (`ruby -v`) and scrivomatic (`scrivomatic -h`) you are using...

**Comment by iandol** [comment]
I'll go ahead and close this, do let me know if you still see it and we can reopen...

**Comment by oWretch** [comment]
It's working correctly for me now after updating to 498ea96.

Thanks Ian.
