### ISSUE TITLE
Character style vs. character format

### ISSUE THREAD

**Issue by gwijthoff** [iandol/scrivomatic#14]
When I compile to pandoc markdown using scrivomatic, none of the text I've italicized in my document is prefixed/suffixed with `*`. It seems like this comes down to a difference between **character format** (i.e. hitting cmd-i to italicize text), and **character styles** (i.e. selecting "emphasis" from the styles pane). Scrivomatic will only add prefixes/suffixes to the latter. But it is infinitely most intuitive while writing to hit cmd-i rather than stopping to highlight text, select the styles pane, and click "emphasis."

Another reason for the importance of converting character formats to pandoc markdown is that character styles cannot be selected when editing Scrivener footnotes. So, there is no way to italicize footnote text in scrivomatic's markdown output.

So, is there a way to pass character formats through any of these Scrivener compile filters?

**Comment by iandol** [comment]
I've added the footnotes caveat, and information on how to rebind ⌘B and ⌘I to toggle styles instead of character formats. Thanks!
