### ISSUE TITLE
Possible help with setting this up? Not an actual issue...

### ISSUE THREAD

**Issue by calimammoth** [iandol/scrivomatic#17]
Hi,

I am sorry to bother you but I wondered if you could help me at all in setting up this workflow. I will try to explain where I am up to.

I have the up to date scrivener for mac. I have installed pandoc and pandocomatic. I downloaded and used the scrivomatic template and I have read through the scrivener document and successfully unpacked all of its contents to my desktop in a folder workflow_mmd. Generally it seems to work and I was able to compile and export the scrivener workflow document you made into new dox and html files etc like I think I was supposed to as a test.

Other info. I am using zotero pandoc inline citations in scrivener with the zotpick apple script. This all works and I use marked2 to see how it's looking as I go along.

I am trying to work collaboratively therefore I would like to produce a regular full output from scrivener into a perfectly formatted word document in an academic style.

When I try to compile my own project using your method and files it give me all outputs except from the docx. format which is the main one I need really.

Also would there be a way to make my pandoc citations produce a full bibliography using your method. Up until now I have been doing this by compiling from scrivener into plain text then putting a command through terminal which converts the plain text file into a docx. with a full bibliogrpahy. However, it didn't produce a document which looked nice and formatted well.

The formatting element to all of these methods is what I am struggling to get right you see.

Sorry if I am not being clear, I suppose that is because I am still trying to figure it all out in my head as it is.

Best wishes

**Comment by iandol** [comment]
Hi @calimammoth sorry for the late reply (Github does not notify me when a new issue is posted, very annoying). 

Please post your `scrivomatic.log` — there should be a DOCX being produced so it sounds like a problem somewhere. Also you should be getting a full bibliography, that is the main reason I switched from MMD to Pandoc, and it works fine for me, so again it sounds like a configuration issue. Are you sure your CSL and BIB files are being found by Pandoc?

**Comment by calimammoth** [comment]
Hey there

Thanks.

I actually managed to figure it out a while back now!! Which is great.
Thanks for creating it.

I do have a question, is it possible to have a pdf output?

Cheers mate!
Sam

**Comment by iandol** [comment]
@calimammoth — yes, in fact there are a whole host of ways. PDFs can be generated via either LaTeX or HTML based templates. If you use my dotpandoc templates, I have several templates that generate PDF outputs (see `pdf-refs`/`eisvogel-pdf`/`html-pdf`/`html-refs-pdf`/`tufte-refs-pdf` and a few others in `pandocomatic.yaml` to see how I do this†).

Scrivomatic will also build PDFs from any LaTeX output if you pass the `-b` command line option. So for example, I write all my letters in Scrivener, using the `latex-letter` template and passing `-b` in the compile settings to auto generate the PDF directly (it even opens in in my PDF viewer).

Cheers, Ian!

----------
†: for HTML>PDF I use the awesome tool princeXML, but it watermarks your output for non-commercial use; Pandoc has several other html>PDF engine you can use too).

**Comment by iandol** [comment]
If you have more questions just ask!
