### ISSUE TITLE
pandomatic run by hand , not in script

### ISSUE THREAD

**Issue by luctaesch** [iandol/scrivomatic#20]
(once template files are copied into the compile dir) , see #19 

1/ the command runs ok by hand , but
2/ not in the compile scripts

extract of logs :

:: Running: /usr/local/bin/pandocomatic -c pandocomatic.yaml --debug Workflow.md 
::: env: ruby_executable_hooks: No such file or directory
:: exit status: pid 73223 exit 127

!!!---scrivomatic::runCommand() RETURN non-zero value: /usr/local/bin/pandocomatic -c pandocomatic.yaml --debug Workflow.md !!!
---

 when run by hand it works:

 : -243 ~/Desktop/workflow_mmd
01:48 $ /usr/local/bin/pandocomatic -c pandocomatic.yaml --debug Workflow.md
(4) + converting Workflow.md 3 times:
(3)   - convert Workflow.md -> Workflow.html
pandoc	--standalone \
	--filter=/usr/local/bin/pandoc-citeproc \
	--bibliography=workflow.bib \
	--csl=apa-workflow.csl
(2)   - convert Workflow.md -> Workflow.html
pandoc	--from=markdown \
	--to=html5 \
	--template=custom.html \
	--css=custom.css \
	--standalone \
	--section-divs \
	--self-contained \
	--toc \
	--toc-depth=4 \
	--base-header-level=1 \
	--filter=assimilateMetadata.rb \
	--bibliography=workflow.bib \
	--csl=apa-workflow.csl
(1)   - convert Workflow.md -> Workflow.docx
pandoc	--from=markdown \
	--to=docx \
	--reference-doc=custom.docx \
	--filter=simplifyMetadata.rb \
	--filter=prependAll.rb \
	--standalone \
	--bibliography=workflow.bib \
	--csl=apa-workflow.csl \
	--output=/Users/luc_taesch/Desktop/workflow_mmd/Workflow.docx
Pandocomatic needed 1.8 seconds to convert 'Workflow.md'.

**Comment by luctaesch** [comment]
this is a path issue.
I found that scrivomatic was copied ( not invoked) in workflow.zip, in the script field, 

i changed this by a bash invocation , but it required the SOURCING OF the profile to work.

![image](https://user-images.githubusercontent.com/70765/46869503-5bdea180-ce2c-11e8-8530-525fde9cea55.png)

**Comment by iandol** [comment]
Hm, you mean in my sample workflow.scriv by default it does not work for you? Did you follow the instructions in the Binder item `Resources > INSTRUCTIONS`?

**Comment by luctaesch** [comment]
My mistake. all these 3 issues were linked to a unproper path setup .  
1/ I removed rvm ( to make sure no issues with rbenv, plus 
2/ I had to delete  an install of pandocomadic in /usr/bin/local to make sure it finds the one in shims. 
3/please note that the path you use in scrivomatic put /usr/bin/local before the rbenv shims one, when a default install do the reverse . is is on purpose ?)
Many thnaks anyway for the effort , quite useful tool .

**Comment by iandol** [comment]
Yes I assumed that if someone installed to `/usr/local/bin` they would want that to override a gem installed via rbenv/pip — I do know that Python can install old versions of Pandoc and this also factors into giving `/usr/local/bin` priority. I'll have another think about that now though...
