### ISSUE TITLE
scrivomatic / pandocomatic problems after upgrade

### ISSUE THREAD

**Issue by htvogler** [iandol/scrivomatic#26]
Hi everyone. I have the following problem.

After upgrading to pandocomatic 0.2.5.0 my documents are not converted anymore. I followed all the general instructions [here](https://github.com/iandol/scrivomatic) and the instructions to install ruby 2.6.2 via rbenv [here](https://github.com/iandol/scrivomatic/blob/master/Installing-Ruby.md). I migrated my pandoc data folder from `~/.pandoc` to `~/.local/share/pandoc`. Although all components seem to be in the right place my scrivener documents are not converted anymore. It seems that pandocomatic doesn't take the input.

<img width="807" alt="Screenshot 2019-04-09 at 17 15 08" src="https://user-images.githubusercontent.com/17174253/55812339-15bc7f00-5aeb-11e9-8ff8-ffe639429926.png">

Interestingly, the [Workflow.scriv](https://github.com/iandol/scrivomatic/blob/master/Workflow.scriv.zip) works without any problems.

<img width="810" alt="Screenshot 2019-04-09 at 17 16 34" src="https://user-images.githubusercontent.com/17174253/55812447-4dc3c200-5aeb-11e9-9768-186e9f0f87a4.png">

Does anyone have an idea what I'm missing here? Thanks for any kind of help!

**Comment by htvogler** [comment]
Okay, I figured it out. For whatever reason, Scrivener populated the metadata in the Compile dialog with the "Title" and "Author" fields.

<img width="327" alt="Screenshot 2019-04-10 at 09 24 38" src="https://user-images.githubusercontent.com/17174253/55860021-96bf5900-5b73-11e9-9d60-5d569a758fe9.png">


This led to an additional block of metadata in the .mmd file that is initially produced by Scrivener.

<img width="961" alt="Screenshot 2019-04-10 at 09 25 28" src="https://user-images.githubusercontent.com/17174253/55860038-9fb02a80-5b73-11e9-9006-7fc6865bbfc1.png">

Once the Scrivener metadata are deleted, everything works as expected.

**Comment by htdebeer** [comment]
Your example should have worked; having two metadata blocks in one file should not matter for pandocomatic to recognize the `pandocomatic_` property regardless if that property is in the first or second YAML metadata block.

I will investigate this from my end; I have created an [issue](https://github.com/htdebeer/pandocomatic/issues/67) for it.

**Comment by htdebeer** [comment]
I found the issue in pandocomatic and fixed it. If you install pandocomatic 0.2.5.1 and try your original scenario again, does it work as expected?

**Comment by iandol** [comment]
Wow, very fast fix, thanks Huub!

**Comment by htvogler** [comment]
Yes, works perfectly now! Thank you very much for the quick fix, Huub.
Also huge thanks to you, Ian. The scrivomatic/pandocomatic workflow saves me a lot of time!
