### ISSUE TITLE
Compiling from scrivener

### ISSUE THREAD

**Issue by anjaroyne** [iandol/scrivomatic#29]
I am trying to follow the directions for installing pandocomatic and scrivomatic in order to compile a scrivener manuscript containing equations to docx. 

So far I can get the math to compile correctly and the figures are also inserted correctly, but I don't get the layout specified in the template (text justified, etc) or given in the scrivener file. There is also no scrivomatic.log file generated.

I suspect there is a problem with correct paths or folders, but I cannot find it. Any suggestions for where to look would be very much appreciated. 

Thanks, Anja

**Comment by iandol** [comment]
I put my templates into a subfolder of the the Pandoc data directory, for example `~/.local/share/pandoc/templates/custom.docx`. I put my `pandocomatic.yaml` into the root of that same folder, i.e. `~/.local/share/pandoc/pandocomatic.yaml`.  In my `pandocomatic.yaml` I use relative paths so for docx the setting is `reference-doc: templates/custom.docx` — pandocomatic uses the pandoc data dir by default (https://github.com/iandol/dotpandoc/blob/master/pandocomatic.yaml#L62)...

The point that you are not getting a scrivomatic.log means you have not set up the compile post-processing command up (https://github.com/iandol/scrivomatic/blob/master/images/processing.png). Without a log it is hard to know what the problems may be with the paths. If you can create a minimal project that is failing you can zip it up here, and please let me also know where you store your `pandocomatic.yaml` and other files.

**Comment by anjaroyne** [comment]
I tried again to follow all your instructions for where to place the pandoc files, and downloaded your workflow files to workflow_mmd on the desktop. I extracted the template files into workflow_mmd (no subfolder) and also put Workflow.scriv in the same folder. When I compile using the Scrivomatic project format, I do get a .log file, but no output. It seems like it does not find my pandocomatic file, which is in the pandoc folder. 

=== ------------------------------------------------------ ===
=== Scrivomatic V1.0.26 Report @ 2019-05-18 09:07:27 +0200 ===
=== ------------------------------------------------------ ===
 Working directory: /Users/anja/Desktop/workflow_mmd
 Initiating with Ruby 2.3.7
===------ Input Options: ------===
#<struct Scrivomatic::OPT input="workflow.md", output=nil, to=nil, yaml="pandocomatic.yaml", command="pandocomatic", envpath="/Users/anja/bin:/Library/TeX/texbin:/usr/local/bin", build=false, cleanup=false, verbose=true, dry_run=false, open_log=true, data_dir=nil>
===------ Final ENV PATH: ------===
/Users/anja/bin:/Library/TeX/texbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Scrivener.app/Contents/Resources/MultiMarkdown/bin
===------ TOOL PATHS: ------===
---pandoc: /usr/local/bin/pandoc | V: 2.7.2
---pandocomatic:  | V: 
---ruby: /usr/bin/ruby | V: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
---python: /usr/bin/python
---xelatex: /Library/TeX/texbin/xelatex
---latexmk: /Library/TeX/texbin/latexmk

 … running pandocomatic, please wait …
===------ COMMAND OUTPUT: ------===
Tool doesn't exist!!!

!!!---scrivomatic::runCommand() Couldn't find  to run, please supply a proper path!


When I try to compile my own project, I have placed all the same files as in the workflow_mmd into my project folder (where I store the .scriv file), but I don't se Scrivomatic as a compile option. Instead I chose Pandoc Word Document under Scrivener Formats. This gives med a word file output but no .log file. Images and equations are treated correctly, but it does not use the formats from the template files.

**Comment by anjaroyne** [comment]
Also concerning the compile post-processing command: where do I get to the window that you show in https://github.com/iandol/scrivomatic/blob/master/images/processing.png? I haven't found it in the Scrivener compile options. 

Thanks, Anja

**Comment by elisebell** [comment]
I am having the exact issues that Anja is having as well. (And I would also appreciate pointers about where to find the window displayed in processing.png also, I haven't been able to find it either)
Thanks,
Elise

=== ------------------------------------------------------ ===
=== Scrivomatic V1.0.26 Report @ 2019-05-18 18:14:24 -0600 ===
=== ------------------------------------------------------ ===
 Working directory: /Users/elisebell1/Desktop/workflow_mmd
 Initiating with Ruby 2.3.7
===------ Input Options: ------===
#<struct Scrivomatic::OPT input="workflow.md", output=nil, to=nil, yaml="pandocomatic.yaml", command="pandocomatic", envpath="/Users/elisebell1/bin:/Library/TeX/texbin:/usr/local/bin", build=false, cleanup=false, verbose=true, dry_run=false, open_log=true, data_dir=nil>
===------ Final ENV PATH: ------===
/Users/elisebell1/bin:/Library/TeX/texbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Scrivener.app/Contents/Resources/MultiMarkdown/bin
===------ TOOL PATHS: ------===
---pandoc: /usr/local/bin/pandoc | V: 2.7.2
---pandocomatic:  | V: 
---ruby: /usr/bin/ruby | V: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
---python: /usr/bin/python
---xelatex: /Library/TeX/texbin/xelatex
---latexmk: /Library/TeX/texbin/latexmk

 … running pandocomatic, please wait …
===------ COMMAND OUTPUT: ------===
Tool doesn't exist!!!

!!!---scrivomatic::runCommand() Couldn't find  to run, please supply a proper path!

**Comment by iandol** [comment]
Hi, so neither of your logs is showing that `pandocomatic` is installed. There is a slight wrinkle, thanks to the very old version (2.3.7) of Ruby that comes with macOS: the latest `pandocomatic` requires a newer version (2.4.x) than the macOS default. Please read through this for installing `pandocomatic` with three different methods:

https://github.com/iandol/scrivomatic/blob/master/Installing-Ruby.md 

If you don't want to fiddle with Ruby, the first method installs the last compatible version of `pandocomatic`, so is the easiest, but you should be aware of this older version if you want to eventually use any newer features released since then.

As for where the commandline option is, you must make sure you are using the **Multimarkdown** compile target:

![Screenshot 2019-05-19 at 12 32 31](https://user-images.githubusercontent.com/153905/57978005-aa919100-7a36-11e9-9689-8d48aec4b217.png)

Then when editing the compile format, it is the last option:

![Screenshot 2019-05-19 at 12 32 19](https://user-images.githubusercontent.com/153905/57978009-b8dfad00-7a36-11e9-9189-4888b55b11e3.png)

Trying to use any of the Pandoc compile targets does not support the post-processing pane that my workflow depends on... HTH.

**Comment by anjaroyne** [comment]
Thanks Ian, 

I had already tried the two different workarounds with ruby described here https://github.com/iandol/scrivomatic/blob/master/Installing-Ruby.md 
I tried again but it didn't change anything. Perhaps I need to uninstall something first since I have tried installing in so many different ways?

 I hadn't tried installing the old version of pandocomatic before, and when I did that now, it was found. However, I got an error running it that I can't work out what to do with. It has something to do with paru. Does this look familiar?

 Working directory: /Users/anja/Desktop/workflow_mmd
 Initiating with Ruby 2.3.7
===------ Input Options: ------===
#<struct Scrivomatic::OPT input="workflow.md", output=nil, to=nil, yaml="pandocomatic.yaml", command="pandocomatic", envpath="/Users/anja/bin:/Users/anja/.rbenv/shims:/Library/TeX/texbin:/usr/local/bin", build=false, cleanup=false, verbose=true, dry_run=false, open_log=true, data_dir=nil>
===------ Final ENV PATH: ------===
/Users/anja/bin:/Users/anja/.rbenv/shims:/Library/TeX/texbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Scrivener.app/Contents/Resources/MultiMarkdown/bin
===------ TOOL PATHS: ------===
---pandoc: /usr/local/bin/pandoc | V: 2.7.2
---pandocomatic: /usr/local/bin/pandocomatic | V: 0.2.5.1
---ruby: /Users/anja/.rbenv/shims/ruby | V: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
---rbenv: /usr/local/bin/rbenv
---python: /usr/bin/python
---xelatex: /Library/TeX/texbin/xelatex
---latexmk: /Library/TeX/texbin/latexmk

 … running pandocomatic, please wait …
===------ COMMAND OUTPUT: ------===
:: Running: /usr/local/bin/pandocomatic -c pandocomatic.yaml --debug workflow.md 
::: (4) + converting /Users/anja/Desktop/workflow_mmd/workflow.md 3 times:
::: (3)   - convert workflow.md -> workflow.docx
::: pandoc	--from=markdown \
::: 	--to=docx \
::: 	--reference-doc=custom.docx \
::: 	--filter=simplifyMetadata.rb \
::: 	--filter=prependAll.rb \
::: 	--standalone \
::: 	--bibliography=workflow.bib \
::: 	--csl=apa-workflow.csl \
::: 	--output=/Users/anja/Desktop/workflow_mmd/workflow.docx
::: /Users/anja/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- paru/filter (LoadError)
::: 	from /Users/anja/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from ./simplifyMetadata.rb:10:in `<main>'
::: Error running filter simplifyMetadata.rb:
::: Filter returned error status 1
::: Error running pandoc => error while running:
::: 
::: pandoc	--from=markdown \
::: 	--to=docx \
::: 	--reference-doc=custom.docx \
::: 	--filter=simplifyMetadata.rb \
::: 	--filter=prependAll.rb \
::: 	--standalone \
::: 	--bibliography=workflow.bib \
::: 	--csl=apa-workflow.csl \
::: 	--output=/Users/anja/Desktop/workflow_mmd/workflow.docx
::: 
::: Pandoc responded with:
::: 
::: /Users/anja/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- paru/filter (LoadError)
::: 	from /Users/anja/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from ./simplifyMetadata.rb:10:in `<main>'
::: Error running filter simplifyMetadata.rb:
::: Filter returned error status 1
::: 
:: exit status: pid 60862 exit 243

!!!---scrivomatic::runCommand() RETURN non-zero value: /usr/local/bin/pandocomatic -c pandocomatic.yaml --debug workflow.md !!!

**Comment by iandol** [comment]
Hi Anja, yes it looks like there is a problem with paru, it looks like you are using the new Ruby (V2.6.3) installed using rbenv, so you can try to cleanup the old gems first then reinstall paru and pandocomatic:

Switch to system ruby:
```shell
rbenv global system; rbenv shell system
```

Uninstall system versions:
```shell
 sudo gem uninstall -f paru pandocomatic -n '/usr/local/bin' 
```

Switch back to modern Ruby and force install latest paru and pandocomatic
```shell
 rbenv global 2.6.3; rbenv shell 2.6.3 
 gem install -f paru pandocomatic
```

Once done, please run this in a terminal: `pandocomatic -v; ruby -v; gem list` and paste the result here...

**Comment by anjaroyne** [comment]
Thanks Ian, it looks like I'm almost there!

I followed the instructions above and got this result in the terminal: 


Pandocomatic version 0.2.5.1
© 2014—2019 Huub de Beer <Huub@heerdebeer.org>

Pandocomatic is free software; pandocomatic is released under the GPLv3.

For more information about pandocomatic run 'pandocomatic --help' or read its
documentation at https://heerdebeer.org/Software/markdown/pandocomatic/.
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

*** LOCAL GEMS ***

bigdecimal (default: 1.4.1)
bundler (default: 1.17.2)
cmath (default: 1.0.0)
csv (default: 3.0.9)
date (default: 2.0.0)
dbm (default: 1.0.0)
did_you_mean (1.3.0)
e2mmap (default: 0.1.0)
etc (default: 1.0.1)
fcntl (default: 1.0.0)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
forwardable (default: 1.2.0)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
json (default: 2.1.0)
logger (default: 1.3.0)
matrix (default: 0.1.0)
minitest (5.11.3)
mutex_m (default: 0.1.0)
net-telnet (0.2.0)
openssl (default: 2.1.2)
optimist (3.0.0)
ostruct (default: 0.1.0)
pandocomatic (0.2.5.1)
paru (0.3.2.0)
power_assert (1.1.3)
prime (default: 0.1.0)
psych (default: 3.1.0)
rake (12.3.2)
rdoc (default: 6.1.0)
rexml (default: 3.1.9)
rss (default: 0.2.7)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
shell (default: 0.7)
stringio (default: 0.0.2)
strscan (default: 1.0.0)
sync (default: 0.5.0)
test-unit (3.2.9)
thwait (default: 0.1.0)
tracer (default: 0.1.0)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
zlib (default: 1.0.0)
****************************

Now it seems like I can compile Workflow without errors: 

===------ TOOL PATHS: ------===
---pandoc: /usr/local/bin/pandoc | V: 2.7.2
---pandocomatic: /Users/anja/.rbenv/shims/pandocomatic | V: 0.2.5.1
---ruby: /Users/anja/.rbenv/shims/ruby | V: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
---rbenv: /usr/local/bin/rbenv
---python: /usr/bin/python
---xelatex: /Library/TeX/texbin/xelatex
---latexmk: /Library/TeX/texbin/latexmk

 … running pandocomatic, please wait …
===------ COMMAND OUTPUT: ------===
:: Running: /Users/anja/.rbenv/shims/pandocomatic -c pandocomatic.yaml --debug workflow.md 
::: (4) + converting /Users/anja/Desktop/workflow_mmd/workflow.md 3 times:
::: (3)   - convert workflow.md -> workflow.docx
::: pandoc	--from=markdown \
::: 	--to=docx \
::: 	--reference-doc=custom.docx \
::: 	--filter=simplifyMetadata.rb \
::: 	--filter=prependAll.rb \
::: 	--standalone \
::: 	--bibliography=workflow.bib \
::: 	--csl=apa-workflow.csl \
::: 	--output=/Users/anja/Desktop/workflow_mmd/workflow.docx
::: (2)   - convert workflow.md -> workflow.html
::: pandoc	--from=markdown \
::: 	--to=html5 \
::: 	--template=custom.html \
::: 	--css=custom.css \
::: 	--standalone \
::: 	--section-divs \
::: 	--self-contained \
::: 	--toc \
::: 	--toc-depth=4 \
::: 	--base-header-level=1 \
::: 	--filter=assimilateMetadata.rb \
::: 	--bibliography=workflow.bib \
::: 	--csl=apa-workflow.csl
::: (1)   - convert workflow.md -> workflow.tex
::: pandoc	--from=markdown \
::: 	--to=latex \
::: 	--template=custom.latex \
::: 	--toc \
::: 	--toc-depth=4 \
::: 	--base-header-level=2 \
::: 	--filter=assimilateMetadata.rb \
::: 	--standalone \
::: 	--bibliography=workflow.bib \
::: 	--csl=apa-workflow.csl
::: Pandocomatic needed 3.8 seconds to convert '/Users/anja/Desktop/workflow_mmd/workflow.md' to 'workflow.md'.
:: exit status: pid 66004 exit 0

However, when I try to compile my own project (I exported the compile format from Workflow and imported it to my own project) it doesn't find the file pandocomatic.yaml, even though I copied it into the folder I am compiling from. In the postprocessing pane the scrivomatic script is inserted in the "edit script" (same text as in Workflow) and in the arguments box I have "<$inputfile>" -l -v -y "pandocomatic.yaml" 2>&1 >>scrivomatic.log (also same as in Workflow). This is the output from the .log file: 

===------ TOOL PATHS: ------===
---pandoc: /usr/local/bin/pandoc | V: 2.7.2
---pandocomatic: /Users/anja/.rbenv/shims/pandocomatic | V: 0.2.5.1
---ruby: /Users/anja/.rbenv/shims/ruby | V: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
---rbenv: /usr/local/bin/rbenv
---python: /usr/bin/python
---xelatex: /Library/TeX/texbin/xelatex
---latexmk: /Library/TeX/texbin/latexmk

 … running pandocomatic, please wait …
===------ COMMAND OUTPUT: ------===
:: Running: /Users/anja/.rbenv/shims/pandocomatic -c pandocomatic.yaml --debug FysikkEnkeltForklart-2-1.md 
::: Config file does not exist: 'pandocomatic.yaml'.
:: exit status: pid 66933 exit 243

!!!---scrivomatic::runCommand() RETURN non-zero value: /Users/anja/.rbenv/shims/pandocomatic -c pandocomatic.yaml --debug FysikkEnkeltForklart-2-1.md !!!

**Comment by elisebell** [comment]
Hi Ian, thanks for your help so far. This is what I'm getting now when I try to compile the workflow document:

=== ------------------------------------------------------ ===
=== Scrivomatic V1.0.26 Report @ 2019-05-20 15:05:36 -0600 ===
=== ------------------------------------------------------ ===
 Working directory: /Users/elisebell1/Desktop/workflow_mmd
 Initiating with Ruby 2.3.7
===------ Input Options: ------===
#<struct Scrivomatic::OPT input="workflow.md", output=nil, to=nil, yaml="pandocomatic.yaml", command="pandocomatic", envpath="/Users/elisebell1/bin:/Users/elisebell1/.rbenv/shims:/Library/TeX/texbin:/usr/local/bin", build=false, cleanup=false, verbose=true, dry_run=false, open_log=true, data_dir=nil>
===------ Final ENV PATH: ------===
/Users/elisebell1/bin:/Users/elisebell1/.rbenv/shims:/Library/TeX/texbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Scrivener.app/Contents/Resources/MultiMarkdown/bin
===------ TOOL PATHS: ------===
---pandoc: /usr/local/bin/pandoc | V: 2.7.2
---pandocomatic: /usr/local/bin/pandocomatic | V: 0.2.5.1
---ruby: /Users/elisebell1/.rbenv/shims/ruby | V: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
---rbenv: /usr/local/bin/rbenv
---python: /usr/bin/python
---xelatex: /Library/TeX/texbin/xelatex
---latexmk: /Library/TeX/texbin/latexmk

 … running pandocomatic, please wait …
===------ COMMAND OUTPUT: ------===
:: Running: /usr/local/bin/pandocomatic -c pandocomatic.yaml --debug workflow.md 
::: (4) + converting /Users/elisebell1/Desktop/workflow_mmd/workflow.md 3 times:
::: (3)   - convert workflow.md -> workflow.docx
::: pandoc	--from=markdown \
::: 	--to=docx \
::: 	--reference-doc=custom.docx \
::: 	--filter=simplifyMetadata.rb \
::: 	--filter=prependAll.rb \
::: 	--standalone \
::: 	--bibliography=workflow.bib \
::: 	--csl=apa-workflow.csl \
::: 	--output=/Users/elisebell1/Desktop/workflow_mmd/workflow.docx
::: /Users/elisebell1/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- paru/filter (LoadError)
::: 	from /Users/elisebell1/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from ./simplifyMetadata.rb:10:in `<main>'
::: Error running filter simplifyMetadata.rb:
::: Filter returned error status 1
::: Error running pandoc => error while running:
::: 
::: pandoc	--from=markdown \
::: 	--to=docx \
::: 	--reference-doc=custom.docx \
::: 	--filter=simplifyMetadata.rb \
::: 	--filter=prependAll.rb \
::: 	--standalone \
::: 	--bibliography=workflow.bib \
::: 	--csl=apa-workflow.csl \
::: 	--output=/Users/elisebell1/Desktop/workflow_mmd/workflow.docx
::: 
::: Pandoc responded with:
::: 
::: /Users/elisebell1/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- paru/filter (LoadError)
::: 	from /Users/elisebell1/.rbenv/versions/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
::: 	from ./simplifyMetadata.rb:10:in `<main>'
::: Error running filter simplifyMetadata.rb:
::: Filter returned error status 1
::: 
:: exit status: pid 75584 exit 243

!!!---scrivomatic::runCommand() RETURN non-zero value: /usr/local/bin/pandocomatic -c pandocomatic.yaml --debug workflow.md !!!

**Comment by iandol** [comment]
@anjaroyne — are you compiling into the same folder or a different one, and if a different one does it have **-mmd** at the end of the name? In general, pandocomatic.yaml is better placed in the Pandoc data dir by default, try to put your pandocomatic.yaml there, then simply remove the `-y pandocomatic.yaml` bit in the arguments — by default pandocomatic looks in the Pandoc data directory.

@elisebell — you have the same error as @anjaroyne had above, try to follow the instructions in https://github.com/iandol/scrivomatic/issues/29#issuecomment-493847932 which fixed anja's problem at least...

**Comment by anjaroyne** [comment]
Yes, it was the _mmd that was not there. Now, after a bit more fiddling around with the compile options and comparing with workflow.md, it is finally working! Thanks again for your help.

**Comment by shartf** [comment]
Hello Ian, 

I thought I might hijack this thread, too :) I've installed rbenv via Homebrew, installed ruby, added path to my ~/.zshrc as advised, installed pandocomatic - all of it went without any errors. However, whey I run the script there is an error: 

=== ------------------------------------------------------ ===
=== Scrivomatic V1.0.26 Report @ 2019-05-22 10:31:11 +0200 ===
=== ------------------------------------------------------ ===
 Working directory: /Users/d067772/Desktop/Code Review UL.md
 Initiating with Ruby 2.6.3
===------ Input Options: ------===
#<struct Scrivomatic::OPT input="Code\\ Review\\ UL.md", output=nil, to=nil, yaml=nil, command="pandocomatic", envpath="/Users/d067772/bin:/Users/d067772/.rbenv/shims:/Library/TeX/texbin:/usr/local/bin:/Users/d067772/.gem/bin", build=false, cleanup=false, verbose=true, dry_run=false, open_log=true, data_dir=nil>
===------ Final ENV PATH: ------===
/Users/d067772/bin:/Users/d067772/.rbenv/shims:/Library/TeX/texbin:/usr/local/bin:/Users/d067772/.gem/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Scrivener.app/Contents/Resources/MultiMarkdown/bin
===------ TOOL PATHS: ------===
---pandoc: /usr/local/bin/pandoc | V: 2.7.2
---pandocomatic: /Users/d067772/.gem/bin/pandocomatic | V: 
---ruby: /Users/d067772/.rbenv/shims/ruby | V: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
---rbenv: /usr/local/bin/rbenv
---python: /usr/local/bin/python
---xelatex: /Library/TeX/texbin/xelatex
---latexmk: /Library/TeX/texbin/latexmk

 … running pandocomatic, please wait …
===------ COMMAND OUTPUT: ------===
:: Running: /Users/d067772/.gem/bin/pandocomatic --debug Code\ Review\ UL.md 
::: /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem pandocomatic (>= 0.a) with executable pandocomatic (Gem::GemNotFoundException)
::: 	from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
::: 	from /Users/d067772/.gem/bin/pandocomatic:23:in `<main>'
:: exit status: pid 59735 exit 1

!!!---scrivomatic::runCommand() RETURN non-zero value: /Users/d067772/.gem/bin/pandocomatic --debug Code\ Review\ UL.md !!!

2 things make me suspicious: 

- there is no version in pandocomatic output
- I had to add ~/.gem/bin/ as path for pandocomatic to be found at all. There is none in /usr/local/bin/

Something went wrong, but the ruby infrastructure is not really my pair of shoes. It seems like it is not executed properly. Maybe because it is not installed properly?

**Comment by elisebell** [comment]
Hi Ian, thanks for your help, I was able to successfully compile the workflow document. Now I'm trying to get everything to work with my own document and I'm running into issues (of course!)

It isn't exactly clear to me from your instructions which files need to go where, so I've tried to emulate the workflow document and folder as much as possible. However, when I compile, I come up against two issues.

First, only an .md and .html file are produced although the frontmatter specifies the same three 'paper-with-refs' templates as the workflow document. I think this has to do with the fact that pandocomatic does not appear to be called during compile, which I don't remember changing.

=== ------------------------------------------------------ ===
=== Scrivomatic V1.0.25 Report @ 2019-05-22 22:55:11 -0600 ===
=== ------------------------------------------------------ ===
 Running under Ruby 2.3.7
 Working directory: /Users/elisebell1/Dropbox/clt_2019_mmd
===------ Input Options: ------===
#<struct Scrivomatic::OPT input="clt_2019.md", output=nil, to=nil, yaml=nil, command="pandocomatic", envpath="/Users/elisebell1/bin:/Users/elisebell1/.rbenv/shims:/Library/TeX/texbin:/usr/local/bin", build=false, cleanup=false, verbose=true, dry_run=false, open_log=true, data_dir=nil>
===------ Final ENV PATH: ------===
/Users/elisebell1/bin:/Users/elisebell1/.rbenv/shims:/Library/TeX/texbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Applications/Scrivener.app/Contents/Resources/MultiMarkdown/bin
===------ TOOL PATHS: ------===
---pandoc: /usr/local/bin/pandoc | V: 2.7.2
---pandocomatic: /Users/elisebell1/.rbenv/shims/pandocomatic | V: 
---ruby: /Users/elisebell1/.rbenv/shims/ruby | V: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
---rbenv: /usr/local/bin/rbenv
---python: /usr/bin/python
---xelatex: /Library/TeX/texbin/xelatex
---latexmk: /Library/TeX/texbin/latexmk

 … running pandocomatic, please wait …
===------ COMMAND OUTPUT: ------===
:: Running: /Users/elisebell1/.rbenv/shims/pandocomatic --debug clt_2019.md 
::: pandoc	
::: Pandocomatic needed 0.4 seconds to convert '/Users/elisebell1/Dropbox/clt_2019_mmd/clt_2019.md' to 'clt_2019.md'.
:: exit status: pid 82771 exit 0

The second issue is that my citations calls are either rendered as text i.e. [@citation2018] or disappear completely i.e. not even plain text where the citation call is. My bibliography file is specified in the frontmatter, and the bib file has been symbolically linked to both the project folder and the ‎⁨⁨Users⁩/⁨elisebell1⁩/.local⁩/share⁩/pandoc⁩, and it is also present in the 'Research' portion of the binder (although I don't think that's necessary, is it?)

I really appreciate everything you've done to create this tool, and I hope I can get it working soon :)

**Comment by iandol** [comment]
@elisebell  Pandocomatic is running I think but the metadata is not present or is not correctly formatted, therefore pandocomatic just does a default html compile with no citations. Without seeing the project or md file it’s hard to know what the problem is, but look at the top of your md doc to see what may be the problem, or zip up a minimal test case and attach it here...

**Comment by elisebell** [comment]
Okay, thanks - I've attached a MWE that has the same issues with compiling only the html file. I've checked the metadata text against the workflow example several times, but I still might be missing something obvious. Thanks!
[mwe.zip](https://github.com/iandol/scrivomatic/files/3217689/mwe.zip)

**Comment by iandol** [comment]
You are not selecting the front matter file in your compile settings:
![Screenshot 2019-05-25 at 13 42 52](https://user-images.githubusercontent.com/153905/58365203-4289f180-7ef3-11e9-9d79-6af053b1e499.png)

Therefore it is not being used. You also need to remove the old metadata as this is already specified in your custom metadata (click the [-] button on title and author).

![Screenshot 2019-05-25 at 13 46 06](https://user-images.githubusercontent.com/153905/58365223-854bc980-7ef3-11e9-81b7-4fcf9d75523d.png)

Finally you do not have a compile format installed in that project, but you may be using a compile format specified on your machine? Without a compile format (scrivomatic is an example but you can make your own), styles won't be converted to Pandoc nor will a post-processor be called.

A final question (I assume you've done this otherwise nothing would work) is whether your pandocomatic.yaml and filters/templates are being stored in your pandoc data directory, if not then unless you put them in the compile folder and explicitly reference them nothing will work properly...

As I've said, my workflow.scriv project is an example where you can see all the files in one place, but that I recommend in general to use the pandoc data directory.

**Comment by elisebell** [comment]
Okay, thank you for your time, but at this point this issue can be closed. I appreciate the work you've put into this tool, but I think your documentation and responses to questions are not sufficient, at least for my needs. Setting up a workflow to use Scrivomatic requires following a lot of steps that, especially with a complicated program like Scrivener, are necessary for unambiguous interpretation. These steps are often skipped over in your directions (or confusing in your images, which do not indicate how to reach the pictured window), to the detriment of the project as a whole. I'm still on the lookout for a workflow that can approach what Scrivomatic was designed to do, and if the instructions are broken down more clearly in the future, I look forward to trying to use it then.
Thanks again for attempting to help,
Elise
