### ISSUE TITLE
Keywords in Pandoc 2

### ISSUE THREAD

**Issue by mijalche** [iandol/scrivomatic#3]
Hi, 
thank you for your solution. It works for me. My question is:
- In Pandoc 2.0 you can convert keywords from .md to .docx. Thus when in yaml you have keywords they will be shown in the docx after the conversion. 
My question is how I can set this in pandocmatic.yaml, thus it is followed during a conversion? Or there is another way, because I can not make it working.
Thank you!

**Comment by iandol** [comment]
Sorry for the late reply (I don't seem to get alerts when issues are made)! 

Where do you want your keywords shown? They should be present in the metadata properties of your Word doc, and it would be possible to make a filter to add them to the actual document too...

**Comment by mijalche** [comment]
Hi, thanks for making a follow up. 

I have somehow creatively used your solution and the available variables in Pandoc to make a nice title page. 
In the reference document I made a keywords style and added in the abstract with span custom-style in order to show it in the text. I used your keywords solution to add keywords in document's metadata. I also used the date variable for the affiliations. 
Maybe not the perfect solution, but I think it uses at maximum the available options.  

Based on that the YAML looks like this
---
title:  This is my title
author: John Doe^1^^, ^^2^
keywords: 
  - for
  - meta
  - tags
date: ^1^ My University First, ^2^ My University Second 
abstract: |
  **Abstract:** This is the abstract.

  <span custom-style=“Keywords”>**Keywords**: for, in , the, text.</span>
...

**Comment by iandol** [comment]
OK, that is a cool soloution! If you wanted to try a filter to do this, perhaps something like this may work:

```ruby
#!/usr/bin/env ruby
# If we have keywords: metadata, convert it to an
# "Keywords" paragraph at the start of the document
# This is because Word template cannot handle this natively

require 'paru/filter'

Paru::Filter.run do
  stop! unless metadata.key?('keywords')
  kw = metadata['keywords']
  text = '**Keywords**: '
  if kw.is_a?(String)
    text += inst
  elsif inst.is_a?(Array)
    inst.each_index do |i|
      text += inst[i].to_s + ', '
    end
    text = text[0..-4]
  elsif inst[0].is_a?(Hash)
    text = 'HASH TODO'
  end
  p = Paru::PandocFilter::Para.new([])
  p.inner_markdown = text
  document.prepend(p)
  stop!
end
```

**Comment by iandol** [comment]
Actually I just pushed a working filter to my dotpandoc repo, this works great for me:

https://github.com/iandol/dotpandoc/blob/master/filters/prependKeywords
