### ISSUE TITLE
get it running

### ISSUE THREAD

**Issue by StefanLindow** [iandol/scrivomatic#32]
Hi Ian,

coming from the user side, I am a bit lost since I dont understand many of the things going on. I simply need to get my scrivener project to be convert in such a way that I can convert citekeys of bibdesk (or zotero) into a certain citation style.

**On the one hand**, I ran your 2018-test workflow [that you posted back then](https://www.literatureandlatte.com/forum/viewtopic.php?f=21&t=50223&start=15). I get this error message:

> === ##################################################### ===
> === Scrivomatic V1.0.11 Report @ 2020-02-04 16:54:54 +0100 ===
>  Running under Ruby 2.6.3
>  Working directory: /Users/administrator/CLOUDSHARE/Doktorarbeit/Writings/#Dissertationsschrift/PRODUCTION_mmd
> ====== Input Options: ======
> #<struct Scrivomatic::OPT input="'workflow.md'", output=nil, to=nil, command="pandocomatic", envpath="/Users/administrator/bin:/usr/local/bin", build=false, verbose=true, dry_run=false>
> ====== Final ENV PATH: ======
> /Users/administrator/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
> ====== TOOL PATHS: ======
> ---pandoc: /usr/local/bin/pandoc | V: 2.9.1.1
> ---pandocomatic: /usr/local/bin/pandocomatic | V: 
> ---ruby: /usr/bin/ruby | V: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
> ---python: /usr/bin/python
> 
>  … running pandocomatic, please wait …
> ====== COMMAND OUTPUT: ======
> :: Running: /usr/local/bin/pandocomatic --debug 'workflow.md' 
> ::: No such template: 'paper-with-refs-docx'.
> :: exit status: pid 3213 exit 243
> !!!---scrivomatic::runCommand() RETURN non-zero value: /usr/local/bin/pandocomatic --debug 'workflow.md' !!!!

**On the other hand:**

I try to follow your general setup, but [the Post-Processing-Script-Step](https://github.com/iandol/scrivomatic#scrivomatic-post-processing-script)does not work either, e.g. I try to make the script usable from terminal like this
> chmod 755 $HOME/bin/scrivomatic
> scrivomatic -h
and getting this:
> -bash: scrivomatic: command not found

I generally wonder if a certain (la)tex setup or anything else except scrivener, MMD, pandoc and pandocomatic is neccessary to run your script. 

** update: for this second thing: the scrivomatic script was saved as a .txt - is that a problem?

**Comment by StefanLindow** [comment]
I solved the first one through take a chance. I wrongly copied the YAML-file into the pandoc folder instead of leaving it within the same as the whole project.

your instructions said that, which I did
> pandocomatic.yaml should be copied to your Pandoc data directory, which is normally ~/.pandoc/.

but your yaml says:

> # Path values are normally relative to the Pandoc data dir: /Users/MYNAME/.pandoc
> # so csl/apa.csl will be searched as /Users/MYNAME/.pandoc/csl/apa.csl — pandocomatic
> # also allows you to use ./ to signify the source folder the markdown file is in.
> # This example uses ./ for all accesory files so copy everything to same locations
> # as the markdown file (Scrivener's compile folder)

**Comment by iandol** [comment]
Hi @StefanLindow sorry for the late reply, I missed this. You seem to be using an old version of the instructions, the pandoc data dir path has changed, and scrivomatic is on V1.0.27, update and recheck...
