### ISSUE TITLE
Style settings

### ISSUE THREAD

**Issue by bilke** [iandol/scrivomatic#4]
Can you please share your Scrivener 3 style settings which can be used with your already linked compile settings?

**Comment by Zimuchen** [comment]
Just a blank project with your style will be OK. Thank you very much.

**Comment by jslvtr** [comment]
It would be really great to have this! Thank you.

**Comment by iandol** [comment]
I have added a sample [Workflow.scriv](https://github.com/iandol/scrivomatic/blob/master/Workflow.scriv.zip), which contains the basic styles for compilation with this workflow...
