### ISSUE TITLE
Request: add homebrew path to scrivomatic

### ISSUE THREAD

**Issue by lyndondrake** [iandol/scrivomatic#47]
The homebrew installation of `pandoc` is in `/opt/homebrew/bin`. If possible, could you please add that path to the list of paths in the environment which `scrivomatic` builds?

**Comment by iandol** [comment]
Hi, this is the path only for M1 machines and I've only ever tested on an Intel Mac...

I've added it to V1.0.31 of scrivomatic, give it a try and see if it works:

https://raw.githubusercontent.com/iandol/scrivomatic/master/scrivomatic

**Comment by lyndondrake** [comment]
That does indeed seem to work. Thank you!

**Comment by iandol** [comment]
Great, I'll make a formal release for this in a while, thanks!
