### ISSUE TITLE
How to create an updated log?

### ISSUE THREAD

**Issue by Reasder** [iandol/scrivomatic#49]
Hi,

Thanks a ton for creating scrivomatic. It's making my workflow so much easier. Love the customization options through pandocomatic.

As someone relatively new to programming, I'm having trouble creating a log of what has happened. Conversion works when it does, but when it doesn't it's up to me to figure out why. I've used the arguments in the screenshot you provide, but I don't get an accurate log. Sometimes console loads but often it displays an outdated log. Are there any resources that you know of that I can use to solve this problem?

**Comment by iandol** [comment]
Yes, console doesn't always seem to refresh the contents (better to close the app before a compile). But the log _should be present as a text file_ in the compile folder and you can open it with your preferred editor. I also create a separate full log from the LaTeX compile if you use the `-b` option and it should also be in your compile folder.

My scrivomatic project **appends** to the log, and perhaps when it fills up it becomes more difficult to read through. You can make it replace the log on each compile by replacing `>>scrivomatic.log` with `>scrivomatic.log` like so in the post-processing pane of the compile format editor:

```shell
-l -v -b "<$inputfile>" >scrivomatic.log 2>&1
```

This will always replace the log, so only the data from the last compile is present.

Let me know how you get on.

**Comment by Reasder** [comment]
Hi, perhaps this requires another thread, but after formatting my computer and reinstalling everything, scrivomatic can't seem to find pandoc anymore:


>  … running pandocomatic, please wait …
> ===------ COMMAND OUTPUT: ------===
> :: Running: /usr/local/bin/pandocomatic --debug example.md 
> ::: Error extracting pandoc's information: No such file or directory - pandoc
> ::: Using made up values instead.
> ::: No such template: 'docx-refs'.
> :: exit status: pid 60101 exit 243
> 
> !!!---scrivomatic::runCommand() RETURN non-zero value: /usr/local/bin/pandocomatic --debug Koan_as_Genre_202211112014.md !!!
> 

Pandocomatic itself works fine, as does the Alfred workflow you've provided. I've added almost any possible environment for pandoc I can think of in scrivener's post-processing tab, but so far no luck. It's merely annoying, not a huge problem.

Thanks for all you do!

Ben

**Comment by iandol** [comment]
@Reasder — Hm, that's a new one 🤣 How is pandoc installed? Can you show me the full log?

**Comment by iandol** [comment]
Note, this can happen if you are using an Apple Silicon machine and older version of scrivomatic, the solution is to update to the latest scrivomatic script, V1.0.33 at least...

**Comment by Reasder** [comment]
Hi Ian, that was exactly the problem. Sorry to bother you with this, and thank you again for writing Scrivomatic. Also, it's now generating logs properly, so both problems were solved at the same time :)

**Comment by iandol** [comment]
Glad it's working!
