### ISSUE TITLE
Working solution?

### ISSUE THREAD

**Issue by admin-teametry** [iandol/scrivomatic#5]
Hi,

I play around with Scrivener 3 and scrivomatic, but I get bad results. As I'm total new to pandoc and so on, I can't configure pandocomatic.yaml properly, because I don't understand what I have to customize for my needs.
Example:
I get a "html" Output, but no "docx" output with your example front-matte entries and don't no why.

Do you have some additional advices or a Scrivener project with proper Settings to get a working solution? 
I appreciate your help a lot.

Thank you and best regards
Andreas

**Comment by iandol** [comment]
I've added a test Workflow.scriv project you can try out: https://github.com/iandol/scrivomatic/blob/master/Workflow.scriv.zip — let me know how it works!

**Comment by admin-teametry** [comment]
Hi Ian,

thank you very much for your replay and the workflow.scriv. It works awfully good :-)

Andreas




On 21. January 2018 at 12:35:38, Ian (notifications@github.com) wrote:

I've added a test Workflow.scriv project you can try out: https://github.com/iandol/scrivomatic/blob/master/Workflow.scriv.zip — let me know how it works!
