### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by tommysundstrom** [iandol/scrivomatic#6]
It seams that you have reorganized, so the link in 

svn export https://github.com/iandol/dotfiles/trunk/pandoc $HOME/.pandoc

is no longer valid.

**Comment by iandol** [comment]
Hi, yes, I moved my pandoc folder to a separate repository, I have updated the link to point to the new repository. Thanks for reporting and sorry for late reply!

https://github.com/iandol/dotpandoc
