### ISSUE TITLE
Failed to find template

### ISSUE THREAD

**Issue by atanasj** [iandol/scrivomatic#7]
Hi. I am getting the following error:

```
=== ##################################################### ===
=== Scrivomatic V1.0.11 Report @ 2018-01-19 23:38:20 +1100 ===
 Running under Ruby 2.3.3
 Working directory: /Users/atanas/Desktop/workflow_mmd
====== Input Options: ======
#<struct Scrivomatic::OPT input="'workflow.md'", output=nil, to=nil, command="pandocomatic", envpath="/Library/TeX/texbin:/Users/atanas/bin:/usr/local/bin", build=false, verbose=true, dry_run=false>
====== Final ENV PATH: ======
/Library/TeX/texbin:/Users/atanas/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
====== TOOL PATHS: ======
---pandoc: /usr/local/bin/pandoc | V: 2.1
---pandocomatic: /usr/local/bin/pandocomatic | V: Pandocomatic version 0.2.2.1
---ruby: /usr/bin/ruby | V: ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
---rbenv: /usr/local/bin/rbenv
---python: /usr/bin/python
---xelatex: /Library/TeX/texbin/xelatex

 … running pandocomatic, please wait …
====== COMMAND OUTPUT: ======
:: Running: /usr/local/bin/pandocomatic --debug 'workflow.md' 
::: No such template: 'paper-with-refs-docx'.
:: exit status: pid 1486 exit 243
!!!---scrivomatic::runCommand() RETURN non-zero value: /usr/local/bin/pandocomatic --debug 'workflow.md' !!!
```

I am following the instruction in the `Scrivener` template you provided.  I've run this multiple times, removing the `paper-with-refs-docx` and putting in line the `paper-with-refs-odt`, or just leaving the `paper-with-refs-html` in the template `YAML metadata`... but no joy.

Not sure what I am doing wrong. Any help would be greatly appreciated. Thanks in advance.

**Comment by iandol** [comment]
Have you moved `pandocomatic.yaml` to your Pandoc data directory (3. in the instructions)? By default it should be at `/Users/yourusername/.pandoc` — this is what the pandocomatic error means...

Let me know how it goes!

**Comment by iandol** [comment]
I updated the sample project and scrivomatic so you can use pandocomatic.yaml in the test folder without having to move it now...
