### ISSUE TITLE
How does your template deal with Equations

### ISSUE THREAD

**Issue by chengs** [iandol/scrivomatic#8]
Hello I download your example project and try to merge it with my workflow. Nevertheless, I do not find how you input math equations inside the scrivener project. Could you please give me some instructions?

**Comment by iandol** [comment]
Hi,

For equations I tend to use styles that generate the standard Pandoc $inlinemath$ and $$blockmath$$ conventions.

So for example $e^{ix}=r(\cos \theta +i\sin \theta ).$ is converted as inlinemaths and:

```

$$x^{\alpha} e^{\beta x^{\gamma} e^{\delta x^{\epsilon}}}$$   

```

as a maths block (blank lines above and below it). I've updated the example Workflow.scriv.zip project to show this. I do not use much maths, at most 3 simple equations per paper, but this should work for a much heavier maths workflow too...

https://github.com/iandol/scrivomatic/blob/master/Workflow.scriv.zip

![screen shot 2018-02-13 at 15 47 56_sml](https://user-images.githubusercontent.com/153905/36155729-6e13d75e-10d5-11e8-9202-09e0dfa24816.png)

**Comment by chengs** [comment]
Thank you for the information!
